### ISSUE TITLE
How to register service without interface

### ISSUE THREAD

**Issue by edsulaiman** [servicetitan/lazy-proxy-serviceprovider#2]
I have a service that is registered as scoped service and can be registered with 
``` csharp
services.AddScoped<MyService>();
```

I want to do the same thing using AddLazyScoped but there is no constructor to do it so
``` shell
There is no argument given that corresponds to the required formal parameter 'implementationFactory' of 'ServiceCollectionExtensions.AddLazyScoped<TService>(IServiceCollection, Func<IServiceProvider, TService>)' [LazyServiceSample]csharp(CS7036) 
```

**Comment by cmendible** [comment]
LazyProxy only works with interfaces. Check the lib code here:

https://github.com/servicetitan/lazy-proxy/blob/1412153166b5cdf42ddfaeca1590d783e363375f/LazyProxy/LazyProxyBuilder.cs#L67
