### ISSUE TITLE
Add the 'Hacktoberfest' topic to the repository.

### ISSUE THREAD

**Issue by cmendible** [servicetitan/lazy-proxy-serviceprovider#7]
@hypercodeplace can we open up this project to hacktoberfest? 

Steps: Add the 'Hacktoberfest' topic to the repository.

**Comment by hypercodeplace** [comment]
@cmendible this is a good idea, thank you for the suggestion. I've added the topic to the repository. Do I need to do something else? Thanks.

**Comment by cmendible** [comment]
@hypercodeplace nothing else my friend! I´m closing this one. Just check if you can opt in the of the repos 😉
